import type { Metadata } from 'next';
import '../styles/globals.css';
import Header from '@/widgets/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: 'cover',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='flex flex-col h-dvh overflow-hidden w-[360px] mx-auto'>
        <Header />
        <main className='flex-1 overflow-y-auto overscroll-contain'>
          {children}
        </main>
      </body>
    </html>
  );
}
