import type { Metadata, Viewport } from 'next';
import '../styles/globals.css';
import Header from '@/widgets/header/header';
import AppProviders from '@/shared/providers/app-providers';
import ModalHost from '@/shared/model/modal/modal-host';

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProviders>
      <html lang='ko'>
        <body className='flex flex-col h-dvh overflow-hidden w-[360px] mx-auto'>
          <Header />
          <main className='max-h-[calc(100%-48px)] h-full overscroll-contain'>
            {children}
          </main>
          <ModalHost />
        </body>
      </html>
    </AppProviders>
  );
}
