import type { Metadata } from 'next';
import '../styles/globals.css';
import Header from '@/widgets/header/Header';
import AppProviders from '@/shared/providers/app-providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: 'cover',
  },
};

export default function RootLayout({
  children,
  modals,
}: Readonly<{
  children: React.ReactNode;
  modals: React.ReactNode;
}>) {
  return (
    <AppProviders>
      <html lang='ko'>
        <body className='flex flex-col h-dvh overflow-hidden w-[360px] mx-auto'>
          <Header />
          <main className='max-h-[calc(100%-48px)] h-full overscroll-contain'>
            {children}
          </main>
          {modals}
        </body>
      </html>
    </AppProviders>
  );
}
